services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: lamvannguyen/digih2o-platform:latest
    container_name: digi_H2O
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - backend_static:/app/static
      - "C:/Program Files/Deltares/Delft3D FM Suite 2023.02 HMWQ/plugins:/host_delft3d"
volumes:
  backend_static:
