version: "3.9"

services:
  backend:
    build: ./backend
    image: vanln/digih2o-platform-backend:latest
    container_name: digih2o_backend
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend/Delft_Projects:/app/Delft_Projects
      - ./backend/static:/app/static

  nginx:
    build: ./nginx
    image: vanln/digih2o-platform-nginx:latest
    container_name: digih2o_nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
