services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: lamvannguyen/digih2o-platform-backend:latest
    container_name: digi_H20
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./backend/Delft_Projects:/app/Delft_Projects
      - ./backend/static:/app/static
      - ./frontend:/app/frontend